name: stratus
description: "Stratus - a calm, honest weather app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
